; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Thu May 12 2022 18:02:18 GMT+0800 (中国标准时间)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


