; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+7 on Thu May 12 2022 18:02:20 GMT+0800 (中国标准时间)

